CREATE TABLE IF NOT EXISTS rating (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS genre (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS film (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(100) NOT NULL,
	description varchar(200),
	release_date date,
	duration INTEGER CHECK (duration > 0),
	rating_id INTEGER REFERENCES rating (id)
);

CREATE TABLE IF NOT EXISTS film_genres (
    film_id INT,
    genre_id INT,
    PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES film(id),
    FOREIGN KEY (genre_id) REFERENCES genre(id)
);

CREATE TABLE IF NOT EXISTS users (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email varchar(100) NOT NULL,
	login varchar(100) NOT NULL,
	name varchar(100),
	birthday date
);

CREATE TABLE IF NOT EXISTS likes (
	film_id INT,
    user_id INT,
    PRIMARY KEY (film_id, user_id),
    FOREIGN KEY (film_id) REFERENCES film(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS friendships (
    user_id INT NOT NULL,
    friend_id INT NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (friend_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS review (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content varchar(250),
    is_positive BOOLEAN,
    user_id INT,
    film_id INT,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (film_id) REFERENCES film(id),
    useful INTEGER DEFAULT 0
)

CREATE TABLE IF NOT EXISTS public.director (
    director_id INTEGER NOT NULL AUTO_INCREMENT,
    director_firstname CHARACTER VARYING(100) NOT NULL,
    director_lastname CHARACTER VARYING(100),
    CONSTRAINT DIRECTOR_PK PRIMARY KEY (director_id)
);

CREATE TABLE IF NOT EXISTS film_directors (
    film_id INTEGER NOT NULL,
    director_id INTEGER NOT NULL,
    PRIMARY KEY (film_id, director_id),
    FOREIGN KEY (film_id) REFERENCES film(id),
    FOREIGN KEY (director_id) REFERENCES director(director_id)
);
